<?php
/**
 * Created by PhpStorm.
 * User: debasiskar
 * Date: 09/01/18
 * Time: 4:50 AM
 */

//echo 9;exit;


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://www.datairis.co/V1/criteria/search/deleteall/consumer");


$data = array('Physical_State'=>'ca');
$data_json = json_encode($data);

$headers = array();
//$headers[] = "TokenID: 7c151f710d05e04dc1098bc0558b7f50d74a";
$headers[] = "TokenID: 52f38a0904543045c30bd4100b6ac1c42eda";
$headers[] = "Content-Type: application/json";
/*$headers[] = "Subscriberusername: GeoAISub";
$headers[] = "Subscriberpassword: reference";
$headers[] = "Accountusername: geoai";
$headers[] = "Accountpassword: reference";
$headers[] = "Accountdetailsrequired: true";*/
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
//curl_setopt($ch, CURLOPT_POSTFIELDS,$data_json);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error :' . curl_error($ch);
}
curl_close ($ch);

print_r($result) ;