<?php
/**
 * Created by PhpStorm.
 * User: debasiskar
 * Date: 09/01/18
 * Time: 4:50 AM
 */

//echo 9;exit;


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://www.datairis.co/V1/criteria/search/addall/consumer");


//$data = array('Physical_State'=>'ca','Ind_Ethnic_Code'=>'A1');
//$data = array('Physical_State'=>'null,Ak,Al','Ind_Ethnic_Code'=>'A1','Income_Code'=>'J'); // household income
//$data = array('Physical_State'=>'Ak,Al'); // household income
//$data = array('Physical_State'=>'ca','Home_Equity_Available_Code'=>'B'); // home value
//$data = array('Physical_City'=>'Phillips');
// $data = array('First_Name'=>'Jim');
//$data = array('Physical_Zip'=>'99524');
//$data = array('Vendor_State_County'=>'04005');
//$data = array('Phone'=>'997.543.6789');
//$data = array('Median_Home_Market_Value'=>'1');
//$data = array('Physical_State'=>'WA','Physical_City'=>'Yelm');
//$data = array('Ind_Household_Rank_Code'=>'1');
//$data = array('Ind_Household_Rank_Code'=>'1,2,3,4,5,6,7,8,9,10');
//$data = array('Area_Code'=>'610,601,502');
//$data = array('Physical_Address'=>'2 Park Ave');
//$data = array('Proximity_Zip_Address_Id'=>'401 Broadway #1703, New York','Proximity_Zip_Id'=>'10013','Proximity_Miles_Id'=>'3');
//$data = array('proximity'=>'2750 NW 3rd Ave|33127|20');
//$data = array('proximity'=>'10013|20');
//$data = array('proximity'=>'#LATLONG#|44.88801549,-93.4075527|2,#LATLONG#|40.872377425012694,-73.63045541015623|2');
//$data = array('proximity'=>'#LATLONG#|44.88801549,-93.4075527|2');

$data = array('proximity'=>'#POLYGON#|-105.02792358398438 39.98798808156982,-105.029296875 39.90165427141783, -104.77249145507812 39.903761270174655,-104.77523803710938 39.98798808156982,-105.02792358398438 39.98798808156982');


//$data = array('proximity'=>'#POLYGON#|  -116.455078125 47.41786669725371, -107.75390625 48.477473349055664, -109.423828125 44.923001342833096, -117.158203125 45.72631510756138, -116.455078125 47.41786669725371|-91.845703125 53.76576070415373, -101.42578125 53.60961805205297, -92.373046875 51.08713514258468, -91.845703125 53.76576070415373|');

$data = array('proximity'=>'#POLYGON#|40.71426759727465 -74.02218437495014,40.712380910219544 -74.02209854426167,40.712706204905324 -74.0139446288564,40.714657939645654 -74.01411629023335,40.71426759727465 -74.02218437495014');


//$data = array('proximity'=>'#POLYGON#|-75.50525665283203 40.61195296181129,-75.50525665283203 40.60283034167843,-75.4647445678711 40.60256967709126,-75.4647445678711 40.61377733640382,-75.50525665283203 40.61195296181129');

$data = array('proximity'=>'#POLYGON#|  -75.95947265625 41.544175782757954, -75.8935546875 41.26400126821706, -75.311279296875 41.41247943604137, -75.333251953125 41.642772382585434, -75.95947265625 41.544175782757954');

$data = array('proximity'=>'#POLYGON#|-75.99251595703123 41.57885606529037,-75.91561166015623 41.25754949044462 ,-75.23445931640623 41.44723028558275,-75.33333626953123 41.70201208865449,-75.99251595703123 41.57885606529037');

$data_json = json_encode($data);

$headers = array();
//$headers[] = "TokenID: 7c151f710d05e04dc1098bc0558b7f50d74a";
$headers[] = "TokenID: 52f38a0904543045c30bd4100b6ac1c42eda";
$headers[] = "Content-Type: application/json";
/*$headers[] = "Subscriberusername: GeoAISub";
$headers[] = "Subscriberpassword: reference";
$headers[] = "Accountusername: geoai";
$headers[] = "Accountpassword: reference";
$headers[] = "Accountdetailsrequired: true";*/
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_json);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error :' . curl_error($ch);
}
curl_close ($ch);

print_r($result) ;




